services:
  # Prometheus for scraping metrics from cAdvisor
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor

  # cAdvisor for monitoring resource usage
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    privileged: true
    restart: always

  server_1:
    image: dslb-server
    container_name: server_1
    ports:
      - "8081:5000"
    environment:
      - SERVER_ID=server_1

  server_2:
    image: dslb-server
    container_name: server_2
    ports:
      - "8082:5000"
    environment:
      - SERVER_ID=server_2

  server_3:
    image: dslb-server
    container_name: server_3
    ports:
      - "8083:5000"
    environment:
      - SERVER_ID=server_3
