version: '3.8'

services:
  server_1:
    image: dslb-server
    ports:
      - "8081:5000"
    environment:
      - SERVER_ID=1

  server_2:
    image: dslb-server
    ports:
      - "8082:5000"
    environment:
      - SERVER_ID=2

  server_3:
    image: dslb-server
    ports:
      - "8083:5000"
    environment:
      - SERVER_ID=3
