services:
  server_1:
    image: dslb-server
    container_name: server_1
    ports:
      - "8081:5000"
    environment:
      - SERVER_ID=server_1

  server_2:
    image: dslb-server
    container_name: server_2
    ports:
      - "8082:5000"
    environment:
      - SERVER_ID=server_2

  server_3:
    image: dslb-server
    container_name: server_3
    ports:
      - "8083:5000"
    environment:
      - SERVER_ID=server_3
